# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'ShopFetch' do
  pod 'MagicalRecord'
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ShopFetch

  target 'ShopFetchTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ShopFetchUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
